CREATE TABLE [dbo].[SocialProfile_Instagram_TargetingInformation] (
    [TargetingInformationId]                    INT            IDENTITY (1, 1) NOT NULL,
    [SocialProfileId]                           INT            NULL,
    [IsSystem]                                  BIT            NULL,
    [FollowOn]                                  BIT            NULL,
    [LikeOn]                                    BIT            NULL,
    [UnFollowOn]                                BIT            NULL,
    [StoryViewerOn]                             BIT            NULL,
    [ContactMembersOn]                          BIT            NULL,
    [HashTagsToEngage]                          NVARCHAR (255) NULL,
    [HashTagsToNotEngage]                       NVARCHAR (255) NULL,
    [LocationsToEngage]                         NVARCHAR (255) NULL,
    [GenderEngagmentPref]                       INT            NULL,
    [IncludeBusinessAccounts]                   BIT            NULL,
    [MonOper]                                   BIT            NULL,
    [TueOper]                                   BIT            NULL,
    [WedOper]                                   BIT            NULL,
    [ThuOper]                                   BIT            NULL,
    [FriOper]                                   BIT            NULL,
    [SatOper]                                   BIT            NULL,
    [SunOper]                                   BIT            NULL,
    [ExecutionIntervals]                        NVARCHAR (500) NULL,
    [RandomizeIntervalsDaily]                   BIT            NULL,
    [CreatedOn]                                 DATETIME       NOT NULL,
    [CreatedBy]                                 NVARCHAR (50)  NULL,
    [UpdatedOn]                                 DATETIME       NOT NULL,
    [UpdatedBy]                                 NVARCHAR (50)  NULL,
    [SocialAccAs]                               INT            NULL,
    [FollNewPerDayLim]                          INT            NULL,
    [FollDailyIncreaseLim]                      INT            NULL,
    [FollMaxPerDayLim]                          INT            NULL,
    [UnFollNewPerDayLim]                        INT            NULL,
    [UnFollDailyIncreaseLim]                    INT            NULL,
    [UnFollMaxPerDayLim]                        INT            NULL,
    [LikePerDayLim]                             INT            NULL,
    [LikeDailyIncreaseLim]                      INT            NULL,
    [LikeMaxPerDayLim]                          INT            NULL,
    [ViewStoriesPerDayLim]                      INT            NULL,
    [ViewStoriesDailyIncreaseLim]               INT            NULL,
    [ViewStoriesMaxPerDayLim]                   INT            NULL,
    [CommentPerDayLim]                          INT            NULL,
    [CommentDailyIncreaseLim]                   INT            NULL,
    [CommentMaxPerDayLim]                       INT            NULL,
    [DMPerDayLim]                               INT            NULL,
    [DMDailyIncreaseLim]                        INT            NULL,
    [DMMaxPerDayLim]                            INT            NULL,
    [FollUserProfileImage]                      BIT            NULL,
    [FollUserMinPosts]                          INT            NULL,
    [FollUserPostsLastXDays]                    INT            NULL,
    [FollUseBlackList]                          BIT            NULL,
    [FollCheckPostsCapBlackList]                BIT            NULL,
    [FollDoNotFollowPrivateUser]                BIT            NULL,
    [FollSkipBizAcct]                           BIT            NULL,
    [FollDoNotFollowUsernamewithdigits]         INT            NULL,
    [FollOnlyFollowGender]                      INT            NULL,
    [FollUserLangs]                             NVARCHAR (500) NULL,
    [FollowLikeCommentHashtagsKeywordw]         BIT            NULL,
    [FollowLikeCommentHashtagsKeywordwValue]    INT            NULL,
    [FollowLikeViewCommentTopPosts]             BIT            NULL,
    [FollowLikeViewCommentTopPostsValue]        INT            NULL,
    [AfterFollLikeuserPosts]                    BIT            NULL,
    [AfterFollLikeuserPostsWaitSecsFrom]        INT            NULL,
    [AfterFollLikeuserPostsWaitSecsTo]          INT            NULL,
    [AfterFollCommentUserPosts]                 BIT            NULL,
    [AfterFollViewUserStory]                    BIT            NULL,
    [AfterFollMuteUser]                         BIT            NULL,
    [FollEngageDaily]                           BIT            NULL,
    [FollEngageDailyfollCountFrmUnFollowList]   INT            NULL,
    [FollEngageLikeRecentPost]                  BIT            NULL,
    [FollEngageEnableLikeCommAfterPostLike]     BIT            NULL,
    [FollEngageSendDMAfterLike]                 BIT            NULL,
    [FollEngageViewUserStoryAfterLike]          BIT            NULL,
    [UnFollFollowersAfterMinDays]               BIT            NULL,
    [UnFollFollowersAfterMinDaysVal]            INT            NULL,
    [UnFollDoNotUnFollowLikersOfPosts]          BIT            NULL,
    [UnFollDoNotUnFollowLikersOfPostsCount]     INT            NULL,
    [UnFollDoNotUnFollowCommThatCommented]      BIT            NULL,
    [UnFollDoNotUnFollowCommThatCommentedCount] INT            NULL,
    [UnFollUseWhiteList]                        BIT            NULL,
    [StorVwOnlyPostXMin]                        BIT            NULL,
    [StorVwOnlyPostXMinVal]                     INT            NULL,
    [StorVwLikeUsrPostRcntPost]                 BIT            NULL,
    [StorVwLikeUsrPostRcntPostVal]              INT            NULL,
    [StorVwReply]                               BIT            NULL,
    [StorVwSendDMAfterLike]                     BIT            NULL,
    [CommUsrRecentPosts]                        BIT            NULL,
    [CommUsrRecentPostsVal]                     INT            NULL,
    [CommUsrRecentPostsTypes]                   INT            NULL,
    [CommFltrPostsByLikeCount]                  BIT            NULL,
    [CommDelCommAfterXDays]                     BIT            NULL,
    [CommDelCommAfterXDaysCount]                INT            NULL,
    [CommLine1]                                 NVARCHAR (500) NULL,
    [CommLine2]                                 NVARCHAR (500) NULL,
    [CommLine3]                                 NVARCHAR (500) NULL,
    [CommLine4]                                 NVARCHAR (500) NULL,
    [CommLine5]                                 NVARCHAR (500) NULL,
    [DMShowUnReadMsg]                           BIT            NULL,
    [DMShowPendingReq]                          BIT            NULL,
    [LEXLikeUsrMostRecentPosts]                 BIT            NULL,
    [LEXLikeUsrMostRecentPostsCount]            INT            NULL,
    [LEXUseBlackList]                           BIT            NULL,
    [LEXChkPostCaptionsforBlackList]            BIT            NULL,
    CONSTRAINT [PK_SG2_TargetingInformation] PRIMARY KEY CLUSTERED ([TargetingInformationId] ASC),
    CONSTRAINT [FK_SG2_SocialProfile_TargetingInformation_SG2_SocialProfile] FOREIGN KEY ([SocialProfileId]) REFERENCES [dbo].[SocialProfile] ([SocialProfileId])
);

