CREATE TABLE [dbo].[SocialProfile_Statistics] (
    [SocialStatisticsId] BIGINT          IDENTITY (1, 1) NOT NULL,
    [SocialProfileId]    INT             NOT NULL,
    [Username]           NVARCHAR (50)   NOT NULL,
    [Date]               DATETIME        NOT NULL,
    [FollowersGain]      BIGINT          CONSTRAINT [DF_CustomerStatistics_FollowersGain] DEFAULT ((0)) NULL,
    [Followers]          BIGINT          CONSTRAINT [DF_CustomerStatistics_Followers] DEFAULT ((0)) NULL,
    [Followings]         BIGINT          CONSTRAINT [DF_CustomerStatistics_Followings] DEFAULT ((0)) NULL,
    [FollowingsRatio]    DECIMAL (18, 2) CONSTRAINT [DF_SG2_SocialProfile_Statistics_Followings1] DEFAULT ((0)) NULL,
    [Joiner]             BIGINT          CONSTRAINT [DF_CustomerStatistics_Joiner] DEFAULT ((0)) NULL,
    [Unjoiner]           BIGINT          CONSTRAINT [DF_CustomerStatistics_Unjoiner] DEFAULT ((0)) NULL,
    [Follow]             BIGINT          CONSTRAINT [DF_CustomerStatistics_Follow] DEFAULT ((0)) NULL,
    [Unfollow]           BIGINT          CONSTRAINT [DF_CustomerStatistics_Unfollow] DEFAULT ((0)) NULL,
    [ContactMassage]     BIGINT          CONSTRAINT [DF_CustomerStatistics_ContactMassage] DEFAULT ((0)) NULL,
    [ContactFriends]     BIGINT          CONSTRAINT [DF_CustomerStatistics_ContactFriends] DEFAULT ((0)) NULL,
    [REPinTweetBlog]     BIGINT          CONSTRAINT [DF_CustomerStatistics_RE(Pin/Tweet/Blog] DEFAULT ((0)) NULL,
    [Bump]               BIGINT          CONSTRAINT [DF_CustomerStatistics_Bump] DEFAULT ((0)) NULL,
    [Like]               BIGINT          CONSTRAINT [DF_CustomerStatistics_Like] DEFAULT ((0)) NULL,
    [Comment]            BIGINT          CONSTRAINT [DF_CustomerStatistics_Comment] DEFAULT ((0)) NULL,
    [Engagement]         BIGINT          CONSTRAINT [DF_CustomerStatistics_Engagement] DEFAULT ((0)) NULL,
    [Repost]             BIGINT          CONSTRAINT [DF_CustomerStatistics_Repost] DEFAULT ((0)) NULL,
    [LikeComments]       BIGINT          CONSTRAINT [DF_CustomerStatistics_LikeComments] DEFAULT ((0)) NULL,
    [StoryViewer]        BIGINT          CONSTRAINT [DF_CustomerStatistics_StoryViewer] DEFAULT ((0)) NULL,
    [BlockedFollowers]   BIGINT          CONSTRAINT [DF_CustomerStatistics_BlockedFollowers] DEFAULT ((0)) NULL,
    [CreatedDate]        DATETIME        NOT NULL,
    [UpdateDate]         DATETIME        NULL,
    CONSTRAINT [PK_CustomerStatistics] PRIMARY KEY CLUSTERED ([SocialStatisticsId] ASC),
    CONSTRAINT [FK_SG2_SocialProfile_Statistics_SG2_SocialProfile] FOREIGN KEY ([SocialProfileId]) REFERENCES [dbo].[SocialProfile] ([SocialProfileId])
);

