//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SG2.CORE.MODAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class LikeyAccount
    {
        public int LikeyAccountId { get; set; }
        public string InstaUserName { get; set; }
        public string InstaPassword { get; set; }
        public string Country { get; set; }
        public string City { get; set; }
        public int Gender { get; set; }
        public string HashTag { get; set; }
        public int StatusId { get; set; }
    }
}
