//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SG2.CORE.MODAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SocialProfile_Instagram_TargetingInformation
    {
        public int TargetingInformationId { get; set; }
        public Nullable<int> SocialProfileId { get; set; }
        public Nullable<bool> IsSystem { get; set; }
        public Nullable<bool> IsBrokerDefault { get; set; }
        public Nullable<int> BrokerCustomerId { get; set; }
        public Nullable<bool> FollowOn { get; set; }
        public Nullable<bool> UnFollowOn { get; set; }
        public string HashTagsToEngage { get; set; }
        public string HashTagsToNotEngage { get; set; }
        public string LocationsToEngage { get; set; }
        public string DirectCompetitors { get; set; }
        public Nullable<int> GenderEngagmentPref { get; set; }
        public Nullable<int> IncludeBusinessAccounts { get; set; }
        public Nullable<bool> MonOper { get; set; }
        public Nullable<bool> TueOper { get; set; }
        public Nullable<bool> WedOper { get; set; }
        public Nullable<bool> ThuOper { get; set; }
        public Nullable<bool> FriOper { get; set; }
        public Nullable<bool> SatOper { get; set; }
        public Nullable<bool> SunOper { get; set; }
        public string ExecutionIntervals { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<bool> FollUserProfileImage { get; set; }
        public Nullable<bool> FollUserMinPosts { get; set; }
        public Nullable<int> FollUserMinPostsVal { get; set; }
        public Nullable<bool> FollUserPostsLastXDays { get; set; }
        public Nullable<int> FollUserPostsLastXDaysVal { get; set; }
        public Nullable<bool> FollDoNotFollowUsernamewithdigits { get; set; }
        public Nullable<int> FollDoNotFollowUsernamewithdigitsVal { get; set; }
        public Nullable<bool> FollUserLangs { get; set; }
        public string FollUserLangsList { get; set; }
        public Nullable<bool> AfterFollLikeuserPosts { get; set; }
        public Nullable<bool> AfterFollCommentUserPosts { get; set; }
        public Nullable<bool> AfterFollViewUserStory { get; set; }
        public Nullable<bool> AfterFollCommentUserStory { get; set; }
        public Nullable<bool> AfterFollMuteUser { get; set; }
        public Nullable<bool> UnFollFollowersAfterMinDays { get; set; }
        public Nullable<int> UnFollFollowersAfterMinDaysVal { get; set; }
        public Nullable<bool> UnFollDoNotUnFollowLikersOfPosts { get; set; }
        public Nullable<int> UnFollDoNotUnFollowLikersOfPostsCount { get; set; }
        public Nullable<bool> UnFollDoNotUnFollowCommThatCommented { get; set; }
        public Nullable<int> UnFollDoNotUnFollowCommThatCommentedCount { get; set; }
        public Nullable<bool> UnFollUseWhiteList { get; set; }
        public string WhistListManualUsers { get; set; }
        public string WhilstListImportedUsers { get; set; }
        public string BlackListUsers { get; set; }
        public string BlackListLocations { get; set; }
        public string BlackListHashtags { get; set; }
        public string BlackListWordsManual { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual SocialProfile SocialProfile { get; set; }
    }
}
