//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SG2.CORE.MODAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SocialProfile_Notification
    {
        public long Id { get; set; }
        public string Notification { get; set; }
        public short StatusId { get; set; }
        public int SocialProfileId { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime UpdateOn { get; set; }
        public string UpdatedBy { get; set; }
        public string Mode { get; set; }
    }
}
