//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SG2.CORE.MODAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SocialProfile_Logs
    {
        public int LogFileId { get; set; }
        public Nullable<int> SocialProfileId { get; set; }
        public string LogData { get; set; }
        public Nullable<System.DateTime> LogDateTime { get; set; }
    
        public virtual SocialProfile_Logs SocialProfile_Logs1 { get; set; }
        public virtual SocialProfile_Logs SocialProfile_Logs2 { get; set; }
    }
}
