//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SG2.CORE.DAL.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer_ContactDetail
    {
        public int ContactDetailsId { get; set; }
        public int CustomerId { get; set; }
        public string JobTitle { get; set; }
        public string MobileNumber { get; set; }
        public string PhoneNumber { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string City { get; set; }
        public string Sate { get; set; }
        public string Country { get; set; }
        public string PostalCode { get; set; }
        public string GUID { get; set; }
        public string PhoneCode { get; set; }
        public Nullable<System.DateTime> ScheduleCallDate { get; set; }
        public string Notes { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
