//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SG2.CORE.DAL.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class SG2_QueueAuditDetail
    {
        public int QueueAuditDetailId { get; set; }
        public string TransactionId { get; set; }
        public string StepName { get; set; }
        public string StepDetail { get; set; }
        public Nullable<int> StepStatus { get; set; }
        public string StepError { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public byte[] Base64Image { get; set; }
    }
}
