//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SG2.CORE.DAL.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class SG2_SocialProfile_StatusHistory
    {
        public int SPSHId { get; set; }
        public Nullable<int> SocialProfileId { get; set; }
        public Nullable<int> JVBoxId { get; set; }
        public Nullable<int> JVBoxStatusId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
    
        public virtual SG2_SocialProfile SG2_SocialProfile { get; set; }
    }
}
