//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SG2.CORE.DAL.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class SG2_QueueAudit
    {
        public int QueueAuditId { get; set; }
        public string TransactionId { get; set; }
        public Nullable<short> QueueType { get; set; }
        public Nullable<short> QueueStatus { get; set; }
        public string QueueData { get; set; }
        public string ErrorDescription { get; set; }
        public Nullable<int> ProfileId { get; set; }
        public string JVBoxData { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<int> NoOfAttempts { get; set; }
        public string QueueAction { get; set; }
        public Nullable<int> JVServerId { get; set; }
    }
}
