//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SG2.CORE.DAL.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class SG2_SocialProfile_ProxyMapping
    {
        public int ProxyMappingId { get; set; }
        public int ProxyId { get; set; }
        public int SocialProfileId { get; set; }
    
        public virtual SG2_Proxy SG2_Proxy { get; set; }
        public virtual SG2_SocialProfile SG2_SocialProfile { get; set; }
    }
}
