//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SG2.CORE.DAL.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class SG2_SocialProfile
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SG2_SocialProfile()
        {
            this.SG2_SocialProfile_ProxyMapping = new HashSet<SG2_SocialProfile_ProxyMapping>();
            this.SG2_SocialProfile_Subscription = new HashSet<SG2_SocialProfile_Subscription>();
            this.SG2_SocialProfile_TargetingInformation = new HashSet<SG2_SocialProfile_TargetingInformation>();
            this.SG2_SocialProfile_Statistics = new HashSet<SG2_SocialProfile_Statistics>();
            this.SG2_SocialProfile_StatusHistory = new HashSet<SG2_SocialProfile_StatusHistory>();
        }
    
        public int SocialProfileId { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<int> SocialProfileTypeId { get; set; }
        public Nullable<int> JVBoxId { get; set; }
        public Nullable<int> JVBoxStatusId { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<int> StripeCustomerId { get; set; }
        public string SocialUsername { get; set; }
        public string SocialPassword { get; set; }
        public string SocialProfileName { get; set; }
        public Nullable<int> SocialPrefferedCity { get; set; }
        public Nullable<int> SocialPrefferedCountry { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<short> JVAttempts { get; set; }
        public Nullable<System.DateTime> JVAttemptsBlockedTill { get; set; }
        public Nullable<short> JVAttemptStatus { get; set; }
        public string verificationCode { get; set; }
        public Nullable<bool> IsArchived { get; set; }
    
        public virtual SG2_Customer SG2_Customer { get; set; }
        public virtual SG2_JVBox SG2_JVBox { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SG2_SocialProfile_ProxyMapping> SG2_SocialProfile_ProxyMapping { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SG2_SocialProfile_Subscription> SG2_SocialProfile_Subscription { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SG2_SocialProfile_TargetingInformation> SG2_SocialProfile_TargetingInformation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SG2_SocialProfile_Statistics> SG2_SocialProfile_Statistics { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SG2_SocialProfile_StatusHistory> SG2_SocialProfile_StatusHistory { get; set; }
    }
}
