//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SG2.CORE.DAL.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class SG2_SocialProfile_TargetingInformation
    {
        public int TargetingInformationId { get; set; }
        public int SocialProfileId { get; set; }
        public string Preference1 { get; set; }
        public string Preference2 { get; set; }
        public string Preference3 { get; set; }
        public string Preference4 { get; set; }
        public Nullable<int> Preference5 { get; set; }
        public Nullable<int> Preference6 { get; set; }
        public Nullable<int> Preference7 { get; set; }
        public string Preference8 { get; set; }
        public string Preference9 { get; set; }
        public Nullable<int> Preference10 { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<short> QueueStatus { get; set; }
        public Nullable<int> JVNoOfLikes { get; set; }
        public Nullable<short> JVLikeyStatus { get; set; }
        public Nullable<int> SocialAccAs { get; set; }
    
        public virtual SG2_SocialProfile SG2_SocialProfile { get; set; }
    }
}
