//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SG2.CORE.DAL.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class SG2_Proxy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SG2_Proxy()
        {
            this.SG2_SocialProfile_ProxyMapping = new HashSet<SG2_SocialProfile_ProxyMapping>();
        }
    
        public int ProxyId { get; set; }
        public string ProxyIPNumber { get; set; }
        public string ProxyIPName { get; set; }
        public string BaseCity { get; set; }
        public string BaseCountry { get; set; }
        public string GeoPoints { get; set; }
        public int StatusId { get; set; }
        public Nullable<int> VPSSId { get; set; }
        public string ProxyPort { get; set; }
        public Nullable<int> NoOfMaxRetry { get; set; }
    
        public virtual SG2_VPSSupplier SG2_VPSSupplier { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SG2_SocialProfile_ProxyMapping> SG2_SocialProfile_ProxyMapping { get; set; }
    }
}
