//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SG2.CORE.DAL.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class SG2_VPSSupplier
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SG2_VPSSupplier()
        {
            this.SG2_Proxy = new HashSet<SG2_Proxy>();
        }
    
        public int VPSSId { get; set; }
        public string IssuingISPName { get; set; }
        public string IssuingISPPhone { get; set; }
        public string IssuingISPWebsite { get; set; }
        public string IssuingISPAccount { get; set; }
        public string IssuingISPPassword { get; set; }
        public string IssuingISPMemo { get; set; }
        public int StatusId { get; set; }
        public string IPManageBy { get; set; }
        public string SupportPhone { get; set; }
        public string SupportEmail { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SG2_Proxy> SG2_Proxy { get; set; }
    }
}
