//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SG2.CORE.DAL.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class SG2_SocialProfile_Statistics
    {
        public long SocialStatisticsId { get; set; }
        public int SocialProfileId { get; set; }
        public string Username { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<long> FollowersGain { get; set; }
        public Nullable<long> Followers { get; set; }
        public Nullable<long> Followings { get; set; }
        public Nullable<long> Joiner { get; set; }
        public Nullable<long> Unjoiner { get; set; }
        public Nullable<long> Follow { get; set; }
        public Nullable<long> Unfollow { get; set; }
        public Nullable<long> ContactMassage { get; set; }
        public Nullable<long> ContactFriends { get; set; }
        public Nullable<long> REPinTweetBlog { get; set; }
        public Nullable<long> Bump { get; set; }
        public Nullable<long> Like { get; set; }
        public Nullable<long> Comment { get; set; }
        public Nullable<long> Engagement { get; set; }
        public Nullable<long> Repost { get; set; }
        public Nullable<long> LikeComments { get; set; }
        public Nullable<long> StoryViewer { get; set; }
        public Nullable<long> BlockedFollowers { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<decimal> FollowingsRatio { get; set; }
    
        public virtual SG2_SocialProfile SG2_SocialProfile { get; set; }
    }
}
